import Head from "next/head";
import Card from "~/components/Layout/Card";
import SideSlider from "~/components/Layout/SideSlider";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@600&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet"></link>

      </Head>
      <div className="h-[300px] w-full px-10 py-10 mt-[120px]">
        <h1 className="text-[30px] px-10 font-extrabold">Your Bookmarks</h1>
        <div className="flex h-[300px]  w-full gap-5 px-8 mt-4">
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
        </div>
      </div>
      <div className="h-[350px] px-10 mt-10 ">
        <SideSlider />
      </div>
      {/* ====================================CONVERT PDF======================= */}
      <div className="h-[300px] w-full px-10 mt-8 mb-20">
        <h1 className="text-[30px] px-10 font-extrabold">Convet Bookmarks</h1>
        <div className="flex h-[300px]  w-full gap-5 px-10 mt-4">
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
        </div>
      </div>
     
    </>
  );
}
